--Mostrar todas las columnas
--SHOW COLUMNS FROM PERSON
--@list SHOW COLUMNS FROM PERSON

--DELETE FROM USER_AUTHORISATION;
--DELETE FROM ROLE;
--DELETE FROM USER;
--
--DELETE FROM PRESCRIPTION_DETAILS;
--DELETE FROM PRESCRIPTION;
--DELETE FROM HEALTH_PROFESSIONAL;
--DELETE FROM PATIENT_FAMILYBACKGROUND;
--DELETE FROM PATIENT;
--DELETE FROM PERSON;
--DELETE FROM MEDICAL_CENTER;
--
--DELETE FROM GENERAL_TABLE;
--DELETE FROM CANTON;
--DELETE FROM PROVINCE;
--
--DELETE FROM DB29179_CIE10;
--DELETE FROM MEDICAMENT;

INSERT INTO USER ( SELECT * FROM CSVREAD('resources/csv/core/user.csv') );
INSERT INTO ROLE ( SELECT * FROM CSVREAD('resources/csv/core/role.csv') );
INSERT INTO USER_AUTHORISATION ( SELECT * FROM CSVREAD('resources/csv/core/user_authorisation.csv') );

ALTER TABLE GENERAL_TABLE ALTER COLUMN id RESTART WITH 1;
INSERT INTO GENERAL_TABLE ( SELECT NULL, * FROM CSVREAD('resources/csv/core/general_table.csv') );

ALTER TABLE PROVINCE ALTER COLUMN id RESTART WITH 1;
INSERT INTO PROVINCE ( SELECT * FROM CSVREAD('resources/csv/core/province.csv') );

ALTER TABLE CANTON ALTER COLUMN id RESTART WITH 1;
INSERT INTO CANTON ( SELECT * FROM CSVREAD('resources/csv/core/canton.csv') );

INSERT INTO PERSON ( SELECT * FROM CSVREAD('resources/csv/core/person.csv') );

--CMC package
--Importar las enfermedades en H2

INSERT INTO DB29179_CIE10 ( SELECT * FROM CSVREAD('resources/csv/cmc/CSV_CIE10.csv') );
ALTER TABLE MEDICAL_CENTER ALTER COLUMN id RESTART WITH 1;
INSERT INTO MEDICAL_CENTER ( SELECT * FROM CSVREAD('resources/csv/cmc/medical_center.csv') );

INSERT INTO PATIENT ( SELECT * FROM CSVREAD('resources/csv/cmc/patient.csv') );
INSERT INTO PATIENT_FAMILYBACKGROUND ( SELECT * FROM CSVREAD('resources/csv/cmc/patient_familybackground.csv') );
INSERT INTO HEALTH_PROFESSIONAL ( SELECT * FROM CSVREAD('resources/csv/cmc/health_professional.csv') );
ALTER TABLE MEDICAMENT ALTER COLUMN id RESTART WITH 1;
INSERT INTO MEDICAMENT ( SELECT NULL, * FROM CSVREAD('resources/csv/cmc/medicament.csv') );

INSERT INTO PRESCRIPTION ( SELECT * FROM CSVREAD('resources/csv/cmc/prescription.csv') );
INSERT INTO PRESCRIPTION_DETAILS ( SELECT * FROM CSVREAD('resources/csv/cmc/prescription_details.csv') );
