--SHOW COLUMNS FROM MEDICAL_CENTER;
--ALTER SEQUENCE DISCIPLINE_SEQUENCE RESTART WITH 6;
--SELECT * FROM INFORMATION_SCHEMA.SEQUENCES 
--SELECT * FROM FREQUENCY;
--SELECT * FROM PROFESSION;
--SELECT * FROM GENERAL_TABLE;
--SELECT * FROM PERSON;
--SELECT * FROM USER;
SELECT * FROM ROLE;
--SELECT * FROM USER_AUTHORISATION;


--SELECT * FROM PATIENT;
--SELECT * FROM FAMILY_BACKGROUND;
--DELETE FROM OCCUPATION;
--ALTER TABLE OCCUPATION ALTER COLUMN id RESTART WITH 1;
--INSERT INTO OCCUPATION ( SELECT NULL, * FROM CSVREAD('resources/csv/core/occupation.csv'));

--CALL CSVWRITE('test.csv', 'SELECT * FROM USER_AUTHORISATION', 'fieldDelimiter=');

--DUMP de la base de datos...
--SCRIPT NODATA to '/home/carper/App/web/WEB-INF/h2/app-schema.sql' CHARSET 'UTF-8'
--SCRIPT SIMPLE NOSETTINGS to '/home/carper/App/web/WEB-INF/h2/data.sql' CHARSET 'UTF-8'
